### ISSUE TITLE
Lego parts

### ISSUE THREAD

**Issue by tnguyenh** [CityScope/CSL_Hanoi#10]
Hi, 

we urgently need to determine which lego parts we should buy. So first we should determine what is built in lego parts, and what is not.

- The land plots 4x4x?. Maybe with a 6x6x? cover
- the table ? Or is it in plastic or plexiglass ? What size ? 60x60 or bigger ?
- other buttons, such as gate switches ?

**Comment by tnguyenh** [comment]
More info from Lego website:

- each part is between 0.10€ and 0.20€
- delivery is within 15 days, so we need to order on next monday !!

**Comment by agrignard** [comment]
OK @tnguyenh let's discuss this together today

**Comment by tnguyenh** [comment]
OK skype later...

**Comment by tnguyenh** [comment]
Dear all,

I think that we all agree on the 6x6 design on top, with a 4x4 layer for the scanner. The block design would be like this:

![Sans titre](https://user-images.githubusercontent.com/18676913/67162156-bd9bea80-f361-11e9-97a4-c78e396d8038.png)

This is the cost on Lego website:


![lego](https://user-images.githubusercontent.com/18676913/67162163-d73d3200-f361-11e9-92a6-033d53414958.png)


How many blocks do we order ? We need 64 permanently on the table, and how many more as a reserve for changing the configuration ? With 128 parts in total, that would be 32 parts for each land use (based on 4 types), which would cover half the table. Is it enough ?

**Comment by benoitgaudou** [comment]
Hi all,
I am not an expert, but what I saw on the scanner software is the following:
- It scans at the scale of 1 lego atom (the smallest piece of lego).
- From this matrix, it identifies blocks of 4x4 to give it a code given a set of patterns.
- The dimensions of the grid, but also the size of the pattern could be changed.

But, my point is that: 
- if we have 4x4 identified and 6x6 on the top, this means that the size of meaningfull blocks is not the same as the border elements or interblocks elements. 
I am afraid that the scanner cannot make the good matching.


<img width="529" alt="Screenshot 2019-10-21 at 07 00 50" src="https://user-images.githubusercontent.com/1555274/67168618-8add0b00-f3d0-11e9-9d7f-0d6a5327ba9f.png">

We will have to modify the scanner to express explicitely what should and should not be taken into account. This could be done, not so difficult in fact, but will make us modify the scanner that has been perhaps deeply tested.

**Comment by agrignard** [comment]
The scanned part is still a 4x4, the 6x6 is just to show bigger lego, keep in mind that there is a piece of white plastic as a canvas for the grid so the scanner only see the 4x4

**Comment by benoitgaudou** [comment]
So If there is a plastic piece between lego species, we will get something like that:
(that means the camera will need to scan 5 x 5 matrices (20x20 pixels) in order to get the four meaningful pieces ? )

<img width="752" alt="Screenshot 2019-10-22 at 15 38 08" src="https://user-images.githubusercontent.com/1555274/67270015-fcf14500-f4e1-11e9-8757-05860a684418.png">

**Comment by tnguyenh** [comment]
I am not sure to understand right... there will still be a 8x8 matrix of lego pieces. As in your drawing, the top part is 6x6, with two dots separating the pieces. However this is not visible for the camera. The bottom layer is 15x15, with 1 column out of two (resp row) being void. So you need to scan a 15x15 matrix (60px X 60px).

**Comment by tnguyenh** [comment]
How many blocks do we buy ? 64 for the table, and 64 more for playing ?

**Comment by tnguyenh** [comment]
Tell me if you see any mistake:

![lego2](https://user-images.githubusercontent.com/18676913/67315206-65521d80-f506-11e9-9937-199b050d6485.png)

**Comment by benoitgaudou** [comment]
Hi,
Just to be sure, each piece on the table will be composed of:
- 4 plates 2x2
- 1 plate 6x6
- 6 FLAT tile 1x6

So will have a set of 2 x 64 pieces (in terms of plate 6x6 and Flat Tile 1x6), and we will have enough plates 2x2 to have only full black or full white pieces.

That seems good to me.

**Comment by tnguyenh** [comment]
Yes, that's it. No full white or full black, since it is not possible to see a rotation with the camera.

**Comment by agrignard** [comment]
This seems to be finished thatnks to @tnguyenh and @benoitgaudou
