### ISSUE TITLE
Number of land use type

### ISSUE THREAD

**Issue by tnguyenh** [CityScope/CSL_Hanoi#11]
Hi, 

we have currently 5 land use types (fish, rice, industry, vegetable, urban).

What are the requirements for the scanner ? Should it be 4 pieces (2x2 each), black or white ? Or do we have a little bit more flexibility ?

If we want to change the gate status (open or close) by rotating the legos pieces, we only have 4 possibilities for land use:

10    11    10    11
00    00    01    01

For the two others:
00    11
00    11
rotation cannot be detected.

I think I saw some pieces with another color than black or white (red), is it working, so we have more possibilities ? Otherwise do we keep only 4 land uses ? Or change the rotation to something else for gates opening or closing ?

**Comment by agrignard** [comment]
We only have black and white pieces with this scanner so you're right we have to remove one landuse

**Comment by benoitgaudou** [comment]
The other solution is to find an alternative way to manage gates:
what about a set of buttons that can be pressed to open and close gates?

**Comment by agrignard** [comment]
THis mode of edition is actually really intuitive, we will keep it, so we need to decide which landuse we remove 

So far we have
"Fish", "Rice","Vegetables", "Industrial", "Urban"

From what I understand each of them have a specific behavior, I have the feeling that we coudl merge Industrial and Urban?  or Rice and Vegetables but it seems to me that Rice consume more water than vegetable?

**Comment by agrignard** [comment]
Urban has been removed
