### ISSUE TITLE
Cut the grid with Laser Cut

### ISSUE THREAD

**Issue by agrignard** [CityScope/CSL_Hanoi#14]
Here is the file in a dxf format. The current one is the one working now and if you can find a plastic sheets bigger than 76cm then you can also try with the big one

https://github.com/CityScope/CSL_Hanoi/tree/master/hardware

**Comment by benoitgaudou** [comment]
The description of how to build the table is much to complicate (and precise) for people here (but I would be curious to know places where some pieces of 729.209mm can be done (and when it is useful to do it)).

So for the big transparent acrylic plate, I will change the dimension from 768mm x768mm to 770mm x 770mm.

Do you confirm that we keep the same dxf files ?

**Comment by agrignard** [comment]
Where did you see this number 729.209mm? Indeed it's to precise and maybe due to a conversion between inch and cm

**Comment by benoitgaudou** [comment]
It is on the side panel E, in the pdf to make the table

**Comment by agrignard** [comment]
Provide a 770x770 dxf file

**Comment by benoitgaudou** [comment]
Thanks.
Is it possible to have rounded corner to the square ?
(as the transparent part has been cut with rounded corner)

**Comment by agrignard** [comment]
good idea i will try yes

**Comment by benoitgaudou** [comment]
I do not have the exact value of the curve, but not so big.
Something like a circle arc with a center at 2cm from the corner
PS: I will send the cut tomorrow

**Comment by agrignard** [comment]
I just push 2 new file on 770 square and one 770 rounded

**Comment by agrignard** [comment]
The grid has been successfully laser cutted.
