### ISSUE TITLE
LED Light with potentiometer

### ISSUE THREAD

**Issue by agrignard** [CityScope/CSL_Hanoi#15]
This is the LED light that needs to be bought (the potentiometer is important to control the power of the light)

https://www.amazon.com/GuoTonG-alimentaci%C3%B3n-certificaci%C3%B3n-impermeable-decoraci%C3%B3n/dp/B072WPBR47/ref=sr_1_1_sspa?gclid=EAIaIQobChMIwcfY_JWr5AIVCRgMCh0RPAi-EAAYASAAEgLKLPD_BwE&hvadid=176963702281&hvdev=c&hvlocphy=9002000&hvnetw=g&hvpos=1t1&hvqmt=e&hvrand=15624118030847230050&hvtargid=kwd-99097201284&hydadcr=14080_9624871&keywords=led+strip+with+dimmer&qid=1567187928&s=gateway&sr=8-1-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEzRUMyUTdFMkQ2WUQxJmVuY3J5cHRlZElkPUEwMTYyOTUwMkFLU01BUDRJSDlJMyZlbmNyeXB0ZWRBZElkPUEwMTc3MzEzMVVES1RNM0VKTVZDOSZ3aWRnZXROYW1lPXNwX2F0ZiZhY3Rpb249Y2xpY2tSZWRpcmVjdCZkb05vdExvZ0NsaWNrPXRydWU=

**Comment by agrignard** [comment]
I got the potentiometer and the LED and will travel with it

**Comment by benoitgaudou** [comment]
Will you let them in Hanoi or bring them back in USA?

**Comment by agrignard** [comment]
I can leave it
