### ISSUE TITLE
Projector Settings

### ISSUE THREAD

**Issue by agrignard** [CityScope/CSL_Hanoi#16]
Here is a list of compatible projector with the project
https://www.projectorcentral.com/projectors.cfm?g=1&hide=0&st=1&exp1=1&r=1017&br=4000-7000&c=&w=&db=&ar=&zr=&wt=&ltg=&ll=&wr=&dt=3.0.0&mfg=&p=&t=&pjl=0&pjw=0&pjh=0&td=&is=&i=d&tr=&tr2=&exp5=1&oop=2&sort=pop&sz=15#top

The cheapest one is this one
https://www.projectorcentral.com/Optoma-ZW502.htm for 1400$

**Comment by benoitgaudou** [comment]
We will buy that projector tomorrow:
ViewSonic PG705HD 
(4000 lumen, Full HD, DLP techno)

**Comment by agrignard** [comment]
@benoitgaudou this one is not in the list I sent as it is not a 4K

It can be worth seing with Doanh if he is ok for this one (https://www.projectorcentral.com/Optoma-ZW502.htm ) if you can find it in Hanoi.

We have a lot of experience with Optomoa or BenQ, I don't know about the quality of the viewsonic

**Comment by benoitgaudou** [comment]
The last projector you copy the link is not 4K either, and in the first
list you sent us, the criteria was Full HD,

Keep in mind that a list or a precise reference is useless, as we buy what
we can find here following requierements.

If we combine the three links you sent us (two in the github and one per
email), the requirements was > 4000 lumens, at least XWGA/ Full HD and DLP
techno.

When we combine these 3 criteria, availability and a decent precise, this
one is the best option we found.


Le ven. 8 nov. 2019 à 19:39, Arnaud Grignard <notifications@github.com> a
écrit :

**Comment by tnguyenh** [comment]
If you need more budget for it, we may get some extra money from IRD (themes, 1K max). The problem would be who owns it ?

**Comment by agrignard** [comment]
Ok you're right there is a problem in the link I send, it is supposed to filter with at least 4K (but a good fullHD is maybe enough) , >4000 lumens and DLP but indeed it gives some projector that are not compatible with this.... I didn't check all of them

**Comment by agrignard** [comment]
So depending on the budget I let you make the final choice , I guess the ViewSonic PG705HD is already not to bad even if I don't see it in the list provided

**Comment by benoitgaudou** [comment]
Just for the record, I put it the requirements specified in issue #5 
https://www.projectorcentral.com/projectors.cfm?g=1&hide=0&st=1&exp1=1&r=13&br=4000-7000&c=&w=&db=&ar=&zr=&wt=&ltg=&ll=&wr=&dt=3.0.0&mfg=&p=&t=&pjl=0&pjw=0&pjh=0&td=&is=&i=d&tr=&tr2=&exp5=1&oop=2&sort=pop&sz=15#top

**Comment by benoitgaudou** [comment]
Thank you Tri for the proposition, but when I look at the website of the company where I will buy the projector, there is no 4K projector with enough lumens:
https://tech360.vn/may-chieu-4k

But even if it was available, I cannot see why it is justified to buy a projector with such a resolution, as:
- the picture produced by GAMA has been modified by keystone, which reduces a lot its quality
- the projection area is small (77cmX77cm)
- the projection conditions will be too lighty

@tnguyenh: I think you should discuss with Doanh about how to spend these 1K euros for something else in the exhibition.

**Comment by agrignard** [comment]
Actually none of the following item are a good reason not to have a good quality projector (maybe the first one about keystone but I am not sure actually).  It's not because the area is small that you don't want a good resolution I would actually say the contrary as people will focus on a very small area compare to a 2Mx2M table. The only reason is the budget.

So for this deployment let's agree on the fullHD with as much brightness as possible (it's actually better to have high brighteness and fullHD then low brightness and 4K). Then we will be sure that it will be exactly the same condition as the current deployment in the lab.

**Comment by benoitgaudou** [comment]
Bought.
