### ISSUE TITLE
Review/check Land Use

### ISSUE THREAD

**Issue by benoitgaudou** [CityScope/CSL_Hanoi#17]
The 4 land uses are now : 
- Fishery
- Rice
- vegetables
- Industrials

Please check:
- Fishery: is it the appropriate word ? I am questioning the fish production, whereas in Vietnam there are many shrimp production. ---> aquaculture ?  (in terms of narrative around the model it could also be interesting as shrimp pollutes a lot, they became to be everywhere in the Mekong delta (due to salinization)).
- vegetables: do you mean trees/fruit trees and gardening ?

**Comment by agrignard** [comment]
Aquaculture is better indeed
vegetables: do you mean trees/fruit trees and gardening ? yes but agree we could find better naming

**Comment by agrignard** [comment]
I close this for now , Fishery has been replaced by Aquaculture. If someone has a better idea that vegetables we can reopen the issue
