### ISSUE TITLE
Polygons in the Shapefile of administrative area do not touch well

### ISSUE THREAD

**Issue by benoitgaudou** [CityScope/CSL_Hanoi#18]
See below a random example:

<img width="323" alt="Screenshot 2019-11-09 at 05 35 54" src="https://user-images.githubusercontent.com/1555274/68515244-d63d5780-02b2-11ea-8ee1-b6e66363e9fe.png">

**Comment by agrignard** [comment]
I have been using the simplify method to reduce the number of vertex 

`````
shape<-(simplification(shape,100));
`````

with this value you see it on the screen but not on the table
