### ISSUE TITLE
GUI - overlays

### ISSUE THREAD

**Issue by benoitgaudou** [CityScope/CSL_Hanoi#19]
When running the CityScope experiment, I get the following GUI.
Some remarks:
- on the left: there seems to be an overlay (grey and transparent), but it seems too small for the text.
- the text is on the simulated environment ("Hanoi" is on a river).
- on the right: I was not able to see the outputs

<img width="1009" alt="Screenshot 2019-11-09 at 05 41 08" src="https://user-images.githubusercontent.com/1555274/68515513-db4ed680-02b3-11ea-8e37-3c4ae6d3559e.png">

**Comment by agrignard** [comment]
Yes this is what you have on a computer  display (retina one I guess), the overlay is calibrated in #px for the current projector in MIT which is a fullHD (1920x1080)

**Comment by agrignard** [comment]
The dev mode is just for dev, we could have a dedicated overlay in the experiment but again it depends on the resolution of the screen (I don't know if something we can get in GAML?)

**Comment by agrignard** [comment]
I close this one for now (feel free to repopen it if we notify something wrong with the projector in Hanoi (shoudl be fine if the projector is a fullHD)
