### ISSUE TITLE
Provides a dem for Bac Hung Hai Province

### ISSUE THREAD

**Issue by agrignard** [CityScope/CSL_Hanoi#2]
We will need a dem model in order to replace the generic one call hab10.asc.

**Comment by agrignard** [comment]
@khanhnt do you have any idea if we can find this datasets? It would be usually store in a asc file (digital elevation model)

**Comment by khanhnt** [comment]
I think the guys from BHH company should have it, I will ask them for it.

**Comment by benoitgaudou** [comment]
Hi Arnaud,

I admit that I am sure to see why we need the DEM for such a model.
In particular given the fact the BHH is really flat.
It is so flat that the direction of the water change during the year, given the amount of water from the upstream.

But I took the opensource DEM I can find (http://www.gfd.com.vn/en/data.html), and I cut and merge using QGIS.  
[BHH.tif.zip](https://github.com/CityScope/CSL_Hanoi/files/3774743/BHH.tif.zip)


Cheers

Benoit

**Comment by khanhnt** [comment]
Thanks @benoitgaudou, I have just updated a bit and convert it to the asc file. @agrignard  is it ok if I push it to includes/BachHungHaiData/ folder ?

**Comment by agrignard** [comment]
@khanhnt what do you mean I just updated a bit? Did you change also the resolution? Did you try to integrate it in GAMA? I have nitce yesterday some problem with some specific .asc file (see https://github.com/gama-platform/gama/issues/2901)

Can you send it though this issue as an attached file?

I check the one provide from @benoitgaudou it's interesting although pretty flat indeed I produced but didn't commit a lighter version of the BHH.tiff

**Comment by khanhnt** [comment]
It seems the file Benoit uploaded not fully overlap the whole BHH map, I just recreated the map. I tried to intergrate to Gama, but the file is too big, I am still not successful in loading it. 
Here is the file [bhh_dem_asc.zip](https://github.com/CityScope/CSL_Hanoi/files/3783725/bhh_dem_asc.zip)
