### ISSUE TITLE
Pollution: static_pollution as an agent

### ISSUE THREAD

**Issue by benoitgaudou** [CityScope/CSL_Hanoi#20]
Right now, each element of static_pollution is created as an agent.
 
Is it necessary to keep that, or should we investigate the possibility to have something lighter (review the schedule of static_pollution or 1 agent managing all these pollution elements) ? 
I have not investigated its impact on performances....

**Comment by tnguyenh** [comment]
From my tests it is not really impacting the performance. It is vizualisation that really impacts the performance, however it is fine to replace the agents by something lighter.

**Comment by agrignard** [comment]
see https://github.com/CityScope/CSL_Hanoi/issues/21
