### ISSUE TITLE
Production of static_pollution

### ISSUE THREAD

**Issue by benoitgaudou** [CityScope/CSL_Hanoi#21]
During the simulation, we can observe some pollution points that are created in some specific area of the map. My point is that in some other industrial area, no pollution is created.

I guess I could read the code and find a perfect answer for that, but as a viewer of the model, it is hard to undestand why pollution in only some area and not in other ones.

The additionnal question: which kind of pollution static_pollution is supposed to represent (air, water .... ) ? 

<img width="944" alt="Screenshot 2019-11-09 at 05 53 07" src="https://user-images.githubusercontent.com/1555274/68516172-e4d93e00-02b5-11ea-8d33-08bc248113c4.png">

**Comment by agrignard** [comment]
Yes I agree there is maybe something wrong here, I wonder if it's not because the get are closed.

I think that @tnguyenh can give us is opinion here.

**Comment by tnguyenh** [comment]
Unless there is another problem, this totally normal. It seems that there is almost no water yet in the other industrial areas. So if the industries cannot consume water, they cannot work and don't reject pollution.

Maybe a solution would be to initialize the simulation with some water agents, so as to make the water spatial distribution more uniform.

**Comment by tnguyenh** [comment]
However the way pollution is emitted can be changed. The idea was that industry does not produce polluted water from nowhere, but instead transforms some clean water into polluted water. I have no idea how it works in reality, so we can change that.

**Comment by agrignard** [comment]
See also https://github.com/CityScope/CSL_Hanoi/issues/20
