### ISSUE TITLE
Location of camera and leds

### ISSUE THREAD

**Issue by benoitgaudou** [CityScope/CSL_Hanoi#26]
What is the best location for the camera (in the centre ? on a border?).
What is the best location and orientation for the leds (bottom toward the ceil, on the ceil and toward camera .... ?

**Comment by agrignard** [comment]
https://user-images.githubusercontent.com/3928502/67799101-1a329000-fa5b-11e9-8dc0-5a70b57e087b.png

**Comment by benoitgaudou** [comment]
Thanks for the picture ..... but the leds are outside of the table ...

**Comment by agrignard** [comment]
The led strip are glued inside one of the size panel (the one facing the user), the one that is open on the picture to show the interior of the table.

**Comment by agrignard** [comment]
Any update here? Ideally following the settings in the lab (on the picture) should be fine

I close this issue for now
