### ISSUE TITLE
Simulation speed and layers

### ISSUE THREAD

**Issue by tnguyenh** [CityScope/CSL_Hanoi#27]
The model is currently running very slowly. A great amount of lag is induced by two layers: the landuse and the main_river.

It is related to issue #18 . Both layers require simplification. Maybe main_river can be simplified manually, I will check this.

**Comment by tnguyenh** [comment]
For main_river, there are a lot of vertices, but also a lot of small ponds or lakes. Maybe we should consider removing the smallest ones.

![image](https://user-images.githubusercontent.com/18676913/68666899-13207d00-0545-11ea-91c4-25ee97eea639.png)

**Comment by agrignard** [comment]
I have just created a simple shape with only the red river (I kept the original one also)
We are basically gaining a factor of 10% per step which is not that bad (for the user it's almost the same as the small part of the red river were almost invisible from the table) It goes from 400 agents to 20.

In this commit 
https://github.com/CityScope/CSL_Hanoi/commit/99e3a156f7306305be795e073fbbd2c04a5196f5
<img width="1083" alt="Screen Shot 2019-11-12 at 10 34 44" src="https://user-images.githubusercontent.com/3928502/68685392-1103f180-0538-11ea-8040-090b9713fdaa.png">
