### ISSUE TITLE
Landuse overlapping two cells

### ISSUE THREAD

**Issue by tnguyenh** [CityScope/CSL_Hanoi#28]
Some landuse overlap two cells. That means that two lego bricks can change their type. Do you think it is a problem or a feature ?

The question is important for representing dryness, as water consumption is computed at the cell level. Maybe one landuse should be related to only one cell ?

**Comment by tnguyenh** [comment]
Fixed. Now each landuse is associated to only one cell.

**Comment by agrignard** [comment]
Did you commit it?
