### ISSUE TITLE
Provides a landuse map

### ISSUE THREAD

**Issue by agrignard** [CityScope/CSL_Hanoi#3]
ban do dat.shp migh tbe the good one however it need to be projected in the right coordinate.

**Comment by khanhnt** [comment]
I have just updated the coordinate according to the OpenData, it matches with the OpenData. But, I don't understand why we don't  use the data provided by BHH company directly. It has all needed layers, including landuse, rivers, gates and so on.

**Comment by agrignard** [comment]
@khanhnt  what do you mean by updating the coordinate according to the OpenData?

Did you modify any files? If yes do you think you can commit them?

**Comment by khanhnt** [comment]
I changed the SRC of landuse and also some other layers to match with the layers in OpenData, as you see in the following figure,  if that it you need, I will push it. 
![Screen Shot 2019-08-01 at 14 40 23](https://user-images.githubusercontent.com/5887348/62274743-adfbbc80-b46a-11e9-8f8c-0b663d55d3dd.jpg)

**Comment by agrignard** [comment]
Ok great. That s exactly what we need so now everything is in the same projection. Can you commit your change ?

**Comment by khanhnt** [comment]
Hi Arnaud, it seems I don't have enough permission to commit the files.

**Comment by agrignard** [comment]
I just added you as a contributor you should be able to push now

**Comment by agrignard** [comment]
@khanhnt would it be possible to do it for all the data in the TuiLoiData.

Right now when I open the one in OpenData and the one in TuiLoiData in QGIS they don't all match. Only TramMua.shp seems coherent

**Comment by khanhnt** [comment]
done @agrignard, I have updated the TuiLoiData.

**Comment by agrignard** [comment]
@khanhnt thank you for the contribution here however for now I have to remove the land from the model as it slows down a lot the model (many agent land are used)

I think we need to simplify a lot the landuse layer in order to be able to integrate the and species in the model.

**Comment by agrignard** [comment]
@khanhnt I am working on the landuse data and I see that there is more than 20 different type of landuse 

Would it be possible to have a more simple classification of landuse? Where does thos data come from? is it a vietnamese standard? 

If it's important to keep those data we will then need to document here the usage of the type. For instance what is "Paddy: 2 rotations per year"? Would it be possible to also have a table that indicate the consumption or production of water for each of this type?

**Comment by khanhnt** [comment]
The data come from BHH company. It maybe follow a existence standard. I will ask them for more detail information.

**Comment by agrignard** [comment]
@khanhnt would it be possible to have a less detail map of the landuse? Maybe something at the district level? Right now the Tui Loi Data is too detailed so it's hard to isolate elements
<img width="1085" alt="Screen Shot 2019-10-21 at 13 59 30" src="https://user-images.githubusercontent.com/3928502/67230285-08257180-f40b-11e9-934c-6fed5b4ac6c9.png">

I was thinking to have something with bigger element so it would be easy to identify which landuse is cover by one block

**Comment by khanhnt** [comment]
OK @agrignard,  I will try to update the map myself first. If it is impossible, I will ask the help from researchers in the field

**Comment by agrignard** [comment]
Just for information I already update some data in this commit
https://github.com/CityScope/CSL_Hanoi/commit/35c3bb8696704e372b18593430ce872e756dbe09

Here https://github.com/CityScope/CSL_Hanoi/tree/master/WaterManagement/includes/VNM_adm

For now I think this is enough for what we need. I thus close this issue for now
