### ISSUE TITLE
Slider doesn't work anymore

### ISSUE THREAD

**Issue by agrignard** [CityScope/CSL_Hanoi#31]
Is there a reason why the port has been changed to  

````
int scaningUDPPort <- 9877;
````
In the current state in Cambridge of the master the slider (who is supposed to control the evaporation rate) is currently broken

@benoitgaudou  please provide more information here to fix this issue

**Comment by benoitgaudou** [comment]
The value has been changed during the process of testing the UDP connection, with the fact that:
- the traditional UDP port in GAMA model is 9877
- the UDP port for the Processing code for slider is 9878
- the UDP port for the Scanner is 5000.

For the moment, in Hanoi, as the slider does not work and that we have implemented the UDP update of the grid, the port in the GAMA model should be in accordance with the Scanner.

**Comment by agrignard** [comment]
There is 2 udp one for the slider and one for the scanner. It used to be like this I see only one networking agent now. We should have one for the scanner port 9897 if you want but we should keep also the 9898 for the slider

**Comment by agrignard** [comment]
I reput the arduino slider networking agent in this commit (the slider is working in Boston). So there is 2 agent networking created one for the slider and one for the scanner with 2 different udp port.

https://github.com/CityScope/CSL_Hanoi/commit/c29f3da744c852e8b9c15e8eae2f5ee354cc39e2

I keep this issue open as we need to validate with the Hanoi team that the local scanning is still working (ideally it should be only one boolean to change in GAML and one line in the scanning to switch from local to internet). 
Also I insist that the local scanning shoudl be on only if the cityIO (internet) one doesn't work. One of the main goal of cityIO is to be able to knwo which table are actually working on the planet 

see https://cityscope.media.mit.edu/CS_CityIO/ where we should see cityscope_hanoi when issue #29 will be fixed


Again the master version is the reference one, this PR won't be merge . I don't know  exactly how it has been implemented as it seems there is a confusion between different version mainly due to this PR https://github.com/CityScope/CSL_Hanoi/pull/24
