### ISSUE TITLE
WaterManagement_modulo not working 

### ISSUE THREAD

**Issue by agrignard** [CityScope/CSL_Hanoi#4]
@hqnghi88 WaterManagement_modulo is not working throwing this exception

````
1 occurence in dev0 at cycle 0: Java error: nil value detected
NullPointerException: null
msi.gama.metamodel.topology.grid.GridNeighborhood.getNeighborsIn(GridNeighborhood.java:115)
msi.gama.metamodel.topology.grid.GamaSpatialMatrix$GridPopulation$MinimalGridAgent.getNeighbors(GamaSpatialMatrix.java:1910)
msi.gaml.skills.GridSkill.getNeighbors(GridSkill.java:146)
gaml.additions.GamlAdditions.lambda$96(GamlAdditions.java:211)
msi.gaml.compilation.GamaHelper.run(GamaHelper.java:43)
msi.gaml.variables.Variable.initializeWith(Variable.java:485)
msi.gama.metamodel.topology.grid.GamaSpatialMatrix$GridPopulation.createAgents(GamaSpatialMatrix.java:1580)
in agent dev0
````

**Comment by hqnghi88** [comment]
which version of gama, as i am using the latest (git) and if possible, export your preference then?
Thanks.

**Comment by agrignard** [comment]
Let's try to have this projet running on the 1.8 official release (for the other user that don't use GIT)

**Comment by hqnghi88** [comment]
OK which offcial release ??? And i am working for that official release so i cannot switching recently to older version and also we should know it if it is a bug. Thanks

**Comment by agrignard** [comment]
GAMA1.8_Official_withJDK_Mac_64bits the one of the website (22 of June)

**Comment by benoitgaudou** [comment]
Hi Arnaud,

The version on the website referenced as the GAMA Official is only the
future expected 1.8 Official, once we decided to "freeze" it.
It was been created in order to have all the workflow ready when we decide
to really release it.

Hopefully tomorrow or in 2 days :-)

Benoit

**Comment by agrignard** [comment]
Ok so for now let's move on the GIT version (which will be hopefully the official 1.8 soon)
