### ISSUE TITLE
Model BacHungHai Irrigation System.gaml does not work: wrong file name

### ISSUE THREAD

**Issue by benoitgaudou** [CityScope/CSL_Hanoi#7]
The model `BacHungHai Irrigation System.gaml` shows an error at initialization as a file is missing or a file name is wrong:

```
	file river_shape_file <- shape_file("../includes/TuiLoiData/river_simple_splitted.shp");
	file poi_file <- shape_file("../includes/TuiLoiData/river_poi.shp");
```

**Comment by tnguyenh** [comment]
Is river_simple_splitted.shp supposed to be a clean shapefile ? The current ones in the other models are not connex, so it is currently not possible to implement a proper water flow...

**Comment by agrignard** [comment]
It was just a naming convention. the last commit fixed the issue
