### ISSUE TITLE
Visualization Design Choice

### ISSUE THREAD

**Issue by agrignard** [CityScope/CSL_Hanoi#8]
Right now it's hard to see exactly the role/impact of each landuse.

I don't know exactly how to do that, maybe one simple way could be to emit particul that are the same color as the landuse? Also, how do we represent visually a landuse that consume a lot.

This is purely visual question but that's the one we need now to adress in order to get a successful tangible interface

@benoitgaudou and @tnguyenh do you have any idea on how to put some "contrast" on the landuse behavior?

**Comment by tnguyenh** [comment]
We still need the correct table from Doanh to determine water consumption/pollution level for each land use.

Do you mean that you would like something that is more visual in regard to the table behavior or something to remind the behavior of each land use, for example in legend ?

**Comment by agrignard** [comment]
I mean something more visual on the table itself so the user can understand whats happening

The value can now be guessed what I am saying that it's hard to see now the impact of each landuse of the water. We only see red or blue particle. Maybe one way could be to emit a particle that is the same color as the landuse (with a certain amount depending on the type)

**Comment by tnguyenh** [comment]
For now land plots emit polluted water, which is not specific to each land use, but we can change that. It is more the amount of water that is consumed and the amount of pollution produced that differ from one land use to another.

To make it more visual for now, put a lot of green plots and just one industry plot (the red one). You can see how the pollution is emitted downwards (I need to improve a little bit the behaviour of newly emitted pollutant).

It is easier to visualize the impact of each land use when starting from a specific scenario (that would mean a non-random starting grid), which may not be convenient on a table. So a different color per land use may be a better solution. Should it be enough actually ?

**Comment by tnguyenh** [comment]
Try the new version, the polluted water has the same color as the originating land plot.

Colors should be changed because dark blue plots generate dark blue polluted water, which is the same as the regular water. Green is not a good color for pollution. Or do you think of another visualization ?

**Comment by agrignard** [comment]
Great ! It is easier to tell the story now and follow the particle emited by specific landuse

Agree with you the color are not good for now, green doesn't sound like pollution and Blue is confusing. let's keep it like this for now for debug mode and we will propose a better color palette.

Thakns for the update!

**Comment by agrignard** [comment]
I close this issue and might open other one related to design question.
