### ISSUE TITLE
old model don't work anymore

### ISSUE THREAD

**Issue by agrignard** [CityScope/CSL_Hanoi#9]
The model that were working don't run anymore (e.g WaterManagementOpenGeneric.gaml)

It would be great to keep the model working even when reorganizing the folder.

**Comment by tnguyenh** [comment]
It's in the 'old' folder ? It's not meant to be used anymore...

**Comment by agrignard** [comment]
Doesn't mean it shouldn't work ;-) or we remove it

**Comment by tnguyenh** [comment]
It should be removed, but see it as a reserve for spare parts... we might need to get some code parts to add to the final model, that's why we have not deleted it yet...

Anyway I cleaned it, except for testData because I don't know to what file it refers to.
